Repository IT-MIVHS/E-Lapor, pull requests merged in 2025-07, with the labels that each got.

#27 [Production] Merge Version 1.1.11
  src/components/AboutComponents/AboutNavbar/AboutNavbar.tsx
  src/components/AboutComponents/AboutTutorial/AboutTutorial.astro
  src/components/DashboardComponents/ExportDashboard/ExportPage.tsx
  src/components/DashboardComponents/ExportDashboard/options/DateRangeOptions.tsx
  src/components/DashboardComponents/ExportDashboard/options/FilterOptions.tsx
  src/components/DashboardComponents/ExportDashboard/options/OutputOptions.tsx
  src/components/DashboardComponents/ExportDashboard/options/RowOptions.tsx
  src/components/DashboardComponents/GraphicDashboard/GraphicComponent.tsx
  src/components/DashboardComponents/SettingDashboard/SettingComponent.tsx
  src/components/DashboardComponents/SettingDashboard/SettingPage.tsx
  src/components/DashboardComponents/SidebarAdmin/SidebarAdmin.tsx
  src/components/DashboardComponents/StatisticsDashboard/LineChartComponent.tsx
  src/components/DashboardComponents/StatisticsDashboard/LineChartFilter.tsx
  src/components/DashboardComponents/StatisticsDashboard/PercentContComponent.tsx
  src/components/DashboardComponents/StatisticsDashboard/PieChartComponent.tsx
  src/components/DashboardComponents/StatisticsDashboard/StatisticsPage.tsx
  src/components/DashboardComponents/TableDashboard/Desktop/ReportDesktopTable.tsx
  src/components/DashboardComponents/TableDashboard/Mobile/ReportMobileCard.tsx
  src/components/DashboardComponents/TableDashboard/Mobile/ReportMobileTable.tsx
  src/components/DashboardComponents/TableDashboard/Modals/ReportDetailModal.tsx
  src/components/DashboardComponents/TableDashboard/Modals/ReportEditModal.tsx
  src/components/DashboardComponents/TableDashboard/ReportDetailModal.tsx
  src/components/DashboardComponents/TableDashboard/ReportEditModal.tsx
  src/components/DashboardComponents/TableDashboard/ReportMobileCard.tsx
  src/components/DashboardComponents/TableDashboard/ReportTableComponent.tsx
  src/components/DashboardComponents/TableDashboard/ReportTablePage.tsx
  src/components/DashboardComponents/TableDashboard/ReportTableToolbar.tsx
  src/components/DashboardComponents/TableDashboard/ReportTableWrapper.tsx
  src/components/DashboardComponents/TableDashboard/Toolbar/ReportPagination.tsx
  src/components/DashboardComponents/TableDashboard/Toolbar/ReportTableToolbar.tsx
  src/components/DashboardComponents/TableDashboard/Toolbar/SelectFilterComponent.tsx
  src/components/DashboardComponents/UsersDashboard/UsersPage.tsx
  src/components/DashboardComponents/UsersDashboard/UsersTabComponent.tsx
  src/components/DashboardComponents/WelcomeDashboard/WelcomePage.tsx
  src/components/ReportFormComponents/SelectCampus/SelectCampusOverlay.tsx
  src/hooks/shared/useUserData.tsx
  src/pages/MainPages/_FormReportPage.tsx
  src/pages/MainPages/_index.tsx
  src/pages/MainPages/_wrapper.tsx
  src/pages/api/user/login.ts
  src/pages/dashboard/DashboardPage/_ExportPage.tsx
  src/pages/dashboard/DashboardPage/_GraphicPage.tsx
  src/pages/dashboard/DashboardPage/_SettingPage.tsx
  src/pages/dashboard/DashboardPage/_SideBarToggle.tsx
  src/pages/dashboard/DashboardPage/_TablePage.tsx
  src/pages/dashboard/DashboardPage/_UsersPage.tsx
  src/pages/dashboard/DashboardPage/_WelcomePage.tsx
  src/pages/dashboard/DashboardPage/_index.tsx
  src/pages/dashboard/index.astro
  src/utils/api_helper.ts
Labels: bug, enhancement

#36 [production] Merge Version 1.1.18
  package.json
  src/changelog.json
  src/components/DashboardComponents/ExportDashboard/ExportPage.tsx
  src/components/DashboardComponents/ExportDashboard/options/FilterOptions.tsx
  src/components/DashboardComponents/ExportDashboard/options/OutputOptions.tsx
  src/components/DashboardComponents/ExportDashboard/options/RowOptions.tsx
  src/components/DashboardComponents/SettingDashboard/EditUserDataModal.tsx
  src/components/DashboardComponents/SettingDashboard/SettingPage.tsx
  src/components/DashboardComponents/SidebarAdmin/SidebarAdmin.tsx
  src/components/DashboardComponents/StatisticsDashboard/StatisticsPage.tsx
  src/components/DashboardComponents/StatisticsDashboard/filters/ApplyFilterButton.tsx
  src/components/DashboardComponents/StatisticsDashboard/filters/CampusChartFilter.tsx
  src/components/DashboardComponents/StatisticsDashboard/filters/LocationChartFilter.tsx
  src/components/DashboardComponents/StatisticsDashboard/filters/TimeChartFilter.tsx
  src/components/DashboardComponents/TableDashboard/Desktop/ReportDesktopTable.tsx
  src/components/DashboardComponents/TableDashboard/Mobile/ReportMobileCard.tsx
  src/components/DashboardComponents/TableDashboard/Mobile/ReportMobileTable.tsx
  src/components/DashboardComponents/TableDashboard/Modals/ReportDetailModal.tsx
  src/components/DashboardComponents/TableDashboard/Modals/ReportEditModal.tsx
  src/components/DashboardComponents/TableDashboard/ReportMobileCard.tsx
  src/components/DashboardComponents/TableDashboard/ReportTablePage.tsx
  src/components/DashboardComponents/TableDashboard/Toolbar/ReportTableToolbar.tsx
  src/components/DashboardComponents/TableDashboard/Toolbar/SelectFilterComponent.tsx
  src/components/DashboardComponents/UsersDashboard/UsersPage.tsx
  src/components/DashboardComponents/WelcomeDashboard/WelcomePage.tsx
  src/components/GlobalComponents/DropdownComponent/DropdownComponent.tsx
  src/components/GlobalComponents/VersionTracker/VersionTracker.tsx
  src/hooks/pages/Export/useExportHook.tsx
  src/hooks/shared/useUserData.tsx
  src/layouts/Layout.astro
  src/middleware.ts
  src/pages/api/user/create.ts
  src/pages/api/user/login.ts
  src/pages/api/user/update.ts
  src/pages/dashboard/DashboardPage/_SideBarToggle.tsx
  src/pages/dashboard/index.astro
  src/styles/global.css
  src/types/variables.ts
  src/utils/api_helper.ts
  src/utils/api_interface.ts
  src/utils/db.ts
Labels: bug, enhancement, features, production

#47 [production] Version 1.2.1
  src/components/DashboardComponents/StatisticsDashboard/PICStatisticsDashboard/PICStatisticsDashboard.tsx
  src/components/DashboardComponents/StatisticsDashboard/PICStatisticsDashboard/outputs/PICRankTable.tsx
  src/components/DashboardComponents/StatisticsDashboard/PICStatisticsDashboard/outputs/ReporterRankTable.tsx
  src/components/DashboardComponents/TableDashboard/Desktop/ReportDesktopTable.tsx
  src/components/DashboardComponents/TableDashboard/Mobile/ReportMobileCard.tsx
  src/components/DashboardComponents/TableDashboard/Modals/ReportDetailModal.tsx
  src/hooks/pages/Statistics/useReporterRankHook.tsx
  src/types/error.ts
  src/types/variables.ts
  src/utils/other.ts
Labels: bug, production
